name: Industrialisation continue sur le serveur Alwaysdata

on: push

jobs:
  Connexion:
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH avec le serveur
        uses: appleboy/ssh-action@master
        with:
          host: "ssh-${{ secrets.USERNAME }}.alwaysdata.net"
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            echo "Connexion SSH réussie"

  Copy:
    needs: Connexion
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH et déploiement
        uses: appleboy/ssh-action@master
        with:
          host: "ssh-${{ secrets.USERNAME }}.alwaysdata.net"
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd $HOME/www/
            REPO_NAME=$(basename ${{ github.repository }})
            git clone https://github.com/${{ github.repository }}.git $REPO_NAME
            if [ -d "$HOME/www/metriques-flask" ]; then
              rsync -r "$REPO_NAME/" "$HOME/www/metriques-flask/"
              rm -rf "$REPO_NAME"
            else
              echo "Le répertoire 'metriques-flask' n'existe pas sur votre serveur"
              exit 1
            fi

  Restart:
    needs: Copy
    runs-on: ubuntu-latest
    steps:
      - name: Restart Alwaysdata site
        run: |
          response_code=$(curl -s -o /dev/null -w "%{http_code}" -X POST --basic --user "${{ secrets.ALWAYSDATA_TOKEN }}:" https://api.alwaysdata.com/v1/site/${{ secrets.ALWAYSDATA_SITE_ID }}/restart/)
          if [ "$response_code" -eq 204 ]; then
            echo "✅ Relance de votre site réussie"
          elif [ "$response_code" -eq 404 ]; then
            echo "❌ ALWAYSDATA_SITE_ID incorrect"
            exit 1
          elif [ "$response_code" -eq 401 ]; then
            echo "❌ ALWAYSDATA_TOKEN incorrect"
            exit 1
          else
            echo "❌ Erreur inconnue (code : $response_code)"
            exit 1
          fi
